# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pyeatt/ebnf2tikz

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pyeatt/ebnf2tikz

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pyeatt/ebnf2tikz/CMakeFiles /home/pyeatt/ebnf2tikz//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pyeatt/ebnf2tikz/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ebnf2tikz

# Build rule for target.
ebnf2tikz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ebnf2tikz
.PHONY : ebnf2tikz

# fast build rule for target.
ebnf2tikz/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/build
.PHONY : ebnf2tikz/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named check-tikz

# Build rule for target.
check-tikz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-tikz
.PHONY : check-tikz

# fast build rule for target.
check-tikz/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-tikz.dir/build.make CMakeFiles/check-tikz.dir/build
.PHONY : check-tikz/fast

#=============================================================================
# Target rules for targets named all_targets

# Build rule for target.
all_targets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_targets
.PHONY : all_targets

# fast build rule for target.
all_targets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_targets.dir/build.make CMakeFiles/all_targets.dir/build
.PHONY : all_targets/fast

#=============================================================================
# Target rules for targets named realclean

# Build rule for target.
realclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 realclean
.PHONY : realclean

# fast build rule for target.
realclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/realclean.dir/build.make CMakeFiles/realclean.dir/build
.PHONY : realclean/fast

annot_lexer.o: annot_lexer.cc.o
.PHONY : annot_lexer.o

# target to build an object file
annot_lexer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/annot_lexer.cc.o
.PHONY : annot_lexer.cc.o

annot_lexer.i: annot_lexer.cc.i
.PHONY : annot_lexer.i

# target to preprocess a source file
annot_lexer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/annot_lexer.cc.i
.PHONY : annot_lexer.cc.i

annot_lexer.s: annot_lexer.cc.s
.PHONY : annot_lexer.s

# target to generate assembly for a file
annot_lexer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/annot_lexer.cc.s
.PHONY : annot_lexer.cc.s

annot_parser.o: annot_parser.cc.o
.PHONY : annot_parser.o

# target to build an object file
annot_parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/annot_parser.cc.o
.PHONY : annot_parser.cc.o

annot_parser.i: annot_parser.cc.i
.PHONY : annot_parser.i

# target to preprocess a source file
annot_parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/annot_parser.cc.i
.PHONY : annot_parser.cc.i

annot_parser.s: annot_parser.cc.s
.PHONY : annot_parser.s

# target to generate assembly for a file
annot_parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/annot_parser.cc.s
.PHONY : annot_parser.cc.s

ast.o: ast.cc.o
.PHONY : ast.o

# target to build an object file
ast.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast.cc.o
.PHONY : ast.cc.o

ast.i: ast.cc.i
.PHONY : ast.i

# target to preprocess a source file
ast.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast.cc.i
.PHONY : ast.cc.i

ast.s: ast.cc.s
.PHONY : ast.s

# target to generate assembly for a file
ast.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast.cc.s
.PHONY : ast.cc.s

ast_dump.o: ast_dump.cc.o
.PHONY : ast_dump.o

# target to build an object file
ast_dump.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_dump.cc.o
.PHONY : ast_dump.cc.o

ast_dump.i: ast_dump.cc.i
.PHONY : ast_dump.i

# target to preprocess a source file
ast_dump.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_dump.cc.i
.PHONY : ast_dump.cc.i

ast_dump.s: ast_dump.cc.s
.PHONY : ast_dump.s

# target to generate assembly for a file
ast_dump.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_dump.cc.s
.PHONY : ast_dump.cc.s

ast_layout.o: ast_layout.cc.o
.PHONY : ast_layout.o

# target to build an object file
ast_layout.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_layout.cc.o
.PHONY : ast_layout.cc.o

ast_layout.i: ast_layout.cc.i
.PHONY : ast_layout.i

# target to preprocess a source file
ast_layout.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_layout.cc.i
.PHONY : ast_layout.cc.i

ast_layout.s: ast_layout.cc.s
.PHONY : ast_layout.s

# target to generate assembly for a file
ast_layout.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_layout.cc.s
.PHONY : ast_layout.cc.s

ast_optimizer.o: ast_optimizer.cc.o
.PHONY : ast_optimizer.o

# target to build an object file
ast_optimizer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_optimizer.cc.o
.PHONY : ast_optimizer.cc.o

ast_optimizer.i: ast_optimizer.cc.i
.PHONY : ast_optimizer.i

# target to preprocess a source file
ast_optimizer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_optimizer.cc.i
.PHONY : ast_optimizer.cc.i

ast_optimizer.s: ast_optimizer.cc.s
.PHONY : ast_optimizer.s

# target to generate assembly for a file
ast_optimizer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_optimizer.cc.s
.PHONY : ast_optimizer.cc.s

ast_tikzwriter.o: ast_tikzwriter.cc.o
.PHONY : ast_tikzwriter.o

# target to build an object file
ast_tikzwriter.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_tikzwriter.cc.o
.PHONY : ast_tikzwriter.cc.o

ast_tikzwriter.i: ast_tikzwriter.cc.i
.PHONY : ast_tikzwriter.i

# target to preprocess a source file
ast_tikzwriter.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_tikzwriter.cc.i
.PHONY : ast_tikzwriter.cc.i

ast_tikzwriter.s: ast_tikzwriter.cc.s
.PHONY : ast_tikzwriter.s

# target to generate assembly for a file
ast_tikzwriter.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/ast_tikzwriter.cc.s
.PHONY : ast_tikzwriter.cc.s

diagnostics.o: diagnostics.cc.o
.PHONY : diagnostics.o

# target to build an object file
diagnostics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/diagnostics.cc.o
.PHONY : diagnostics.cc.o

diagnostics.i: diagnostics.cc.i
.PHONY : diagnostics.i

# target to preprocess a source file
diagnostics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/diagnostics.cc.i
.PHONY : diagnostics.cc.i

diagnostics.s: diagnostics.cc.s
.PHONY : diagnostics.s

# target to generate assembly for a file
diagnostics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/diagnostics.cc.s
.PHONY : diagnostics.cc.s

driver.o: driver.cc.o
.PHONY : driver.o

# target to build an object file
driver.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/driver.cc.o
.PHONY : driver.cc.o

driver.i: driver.cc.i
.PHONY : driver.i

# target to preprocess a source file
driver.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/driver.cc.i
.PHONY : driver.cc.i

driver.s: driver.cc.s
.PHONY : driver.s

# target to generate assembly for a file
driver.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/driver.cc.s
.PHONY : driver.cc.s

lexer.o: lexer.cc.o
.PHONY : lexer.o

# target to build an object file
lexer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/lexer.cc.o
.PHONY : lexer.cc.o

lexer.i: lexer.cc.i
.PHONY : lexer.i

# target to preprocess a source file
lexer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/lexer.cc.i
.PHONY : lexer.cc.i

lexer.s: lexer.cc.s
.PHONY : lexer.s

# target to generate assembly for a file
lexer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/lexer.cc.s
.PHONY : lexer.cc.s

main.o: main.cc.o
.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i
.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s
.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/main.cc.s
.PHONY : main.cc.s

nodesizes.o: nodesizes.cc.o
.PHONY : nodesizes.o

# target to build an object file
nodesizes.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/nodesizes.cc.o
.PHONY : nodesizes.cc.o

nodesizes.i: nodesizes.cc.i
.PHONY : nodesizes.i

# target to preprocess a source file
nodesizes.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/nodesizes.cc.i
.PHONY : nodesizes.cc.i

nodesizes.s: nodesizes.cc.s
.PHONY : nodesizes.s

# target to generate assembly for a file
nodesizes.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/nodesizes.cc.s
.PHONY : nodesizes.cc.s

parser.o: parser.cc.o
.PHONY : parser.o

# target to build an object file
parser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/parser.cc.o
.PHONY : parser.cc.o

parser.i: parser.cc.i
.PHONY : parser.i

# target to preprocess a source file
parser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/parser.cc.i
.PHONY : parser.cc.i

parser.s: parser.cc.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/parser.cc.s
.PHONY : parser.cc.s

resolver.o: resolver.cc.o
.PHONY : resolver.o

# target to build an object file
resolver.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/resolver.cc.o
.PHONY : resolver.cc.o

resolver.i: resolver.cc.i
.PHONY : resolver.i

# target to preprocess a source file
resolver.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/resolver.cc.i
.PHONY : resolver.cc.i

resolver.s: resolver.cc.s
.PHONY : resolver.s

# target to generate assembly for a file
resolver.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/resolver.cc.s
.PHONY : resolver.cc.s

util.o: util.cc.o
.PHONY : util.o

# target to build an object file
util.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/util.cc.o
.PHONY : util.cc.o

util.i: util.cc.i
.PHONY : util.i

# target to preprocess a source file
util.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/util.cc.i
.PHONY : util.cc.i

util.s: util.cc.s
.PHONY : util.s

# target to generate assembly for a file
util.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ebnf2tikz.dir/build.make CMakeFiles/ebnf2tikz.dir/util.cc.s
.PHONY : util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... all_targets"
	@echo "... check"
	@echo "... check-tikz"
	@echo "... realclean"
	@echo "... ebnf2tikz"
	@echo "... annot_lexer.o"
	@echo "... annot_lexer.i"
	@echo "... annot_lexer.s"
	@echo "... annot_parser.o"
	@echo "... annot_parser.i"
	@echo "... annot_parser.s"
	@echo "... ast.o"
	@echo "... ast.i"
	@echo "... ast.s"
	@echo "... ast_dump.o"
	@echo "... ast_dump.i"
	@echo "... ast_dump.s"
	@echo "... ast_layout.o"
	@echo "... ast_layout.i"
	@echo "... ast_layout.s"
	@echo "... ast_optimizer.o"
	@echo "... ast_optimizer.i"
	@echo "... ast_optimizer.s"
	@echo "... ast_tikzwriter.o"
	@echo "... ast_tikzwriter.i"
	@echo "... ast_tikzwriter.s"
	@echo "... diagnostics.o"
	@echo "... diagnostics.i"
	@echo "... diagnostics.s"
	@echo "... driver.o"
	@echo "... driver.i"
	@echo "... driver.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... nodesizes.o"
	@echo "... nodesizes.i"
	@echo "... nodesizes.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... resolver.o"
	@echo "... resolver.i"
	@echo "... resolver.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

