wide_choice =
    'BEGIN' , ( variable_reference | function_identifier | procedure_identifier | constant_expression ) , ':=' , expression , 'END' ,
    actual_parameter_list , compound_statement , ';' ;
